#import <Foundation/Foundation.h>

#define HACK(FUNC) \
    int FUNC() { \
        NSLog(@"trying to use disabled functionality %s", #FUNC); \
        return -1; \
    }

HACK(avio_open_dyn_buf)
HACK(av_init_packet)
HACK(swr_convert)
HACK(avio_close_dyn_buf)
HACK(av_frame_get_best_effort_timestamp)
HACK(av_frame_get_pkt_duration)
HACK(avcodec_send_packet)
HACK(avcodec_receive_frame)
HACK(av_packet_unref)
HACK(av_get_default_channel_layout)
HACK(swr_free)
HACK(av_image_alloc)
HACK(sws_scale)
HACK(avcodec_alloc_context3)
HACK(av_read_frame)
HACK(av_register_all)
HACK(av_free)
HACK(avcodec_parameters_to_context)
HACK(avformat_network_init)
HACK(av_strerror)
HACK(av_seek_frame)
HACK(av_dict_set_int)
HACK(av_samples_get_buffer_size)
HACK(swr_alloc_set_opts)
HACK(av_freep)
HACK(sws_freeContext)
HACK(av_codec_set_pkt_timebase)
HACK(avio_write)
HACK(av_dict_count)
HACK(avio_wb32)
HACK(avcodec_free_context)
HACK(av_dict_get)
HACK(swr_init)
HACK(avformat_free_context)
HACK(av_log_set_callback)
HACK(av_frame_alloc)
HACK(avcodec_close)
HACK(avformat_alloc_context)
HACK(av_dict_free)
HACK(av_dict_set)
HACK(avcodec_find_decoder)
HACK(avformat_find_stream_info)
HACK(sws_getCachedContext)
HACK(avformat_open_input)
HACK(avcodec_flush_buffers)
HACK(avcodec_open2)
HACK(avformat_close_input)

